version: '3.3'
services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "tutorialDB"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: priyanka.padhi@tntra.io
      PGADMIN_DEFAULT_PASSWORD: Start!23
    restart: always

volumes:

  pg_data:
    driver: local

